### ISSUE TITLE
Add test metadata to dashboard

### ISSUE THREAD

**Issue by brandomr** [DARPA-ASKEM/integration-dashboard#3]
This issue is to add core metadata about the test to report generation and subsequently add it to the dashboard. This should include both the version (or commit hash) as well as hosting information for the MIT, SKEMA and Cosmos services. It should also include the version information for Knowledge Middleware Service as well.

Ideally it includes links to the version/commit for each relevant service. 

Ideally it _clearly_ indicates whether a TA1 service is self-hosted by TA1 or hosted by TA4 for the test generation.

**Comment by YohannParis** [comment]
See row 8 to find which TA1 services has implemented this feature:
https://docs.google.com/spreadsheets/d/1OXrJRNdUP7va0YQLtNC_yVB2_aowWQ8iUyE3yocCcMI/edit?pli=1#gid=0

**Comment by fivegrant** [comment]
@brandomr this may need to be reopened in knowledge service. The most recent push to main can now technically writes this data to a table. With this [KM PR](https://github.com/DARPA-ASKEM/knowledge-middleware/pull/57), we get the service source (URL) BUT the version is marked as 'UNAVAILABLE' since the table that @YohannParis indicates that nobody has implemented a version endpoint. (I remember one or two teams say they already have it but that just means the above table needs to be updated)

**Comment by fivegrant** [comment]
Example: 
![image](https://github.com/DARPA-ASKEM/integration-dashboard/assets/14170067/3c5524f1-efad-4db3-a079-e238e2388e7d)

**Comment by fivegrant** [comment]
https://github.com/DARPA-ASKEM/knowledge-middleware/pull/63#event-10464698869
