### ISSUE TITLE
Add a button that kicks off a new run

### ISSUE THREAD

**Issue by Sorrento110** [DARPA-ASKEM/integration-dashboard#8]
This is BLOCKED until we have a mechanism to run test suite via GitHub actions.

**Comment by fivegrant** [comment]
@brandomr I think we should close this issue because I don't think we can get around the security issues of exposing a publicly accessible button that will execute CI code on a public site. I think solving https://github.com/DARPA-ASKEM/knowledge-middleware/issues/118 will serve a similar purpose though.
